ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
require_relative '../../node_modules/react-native/scripts/react_native_pods'
platform :ios, '15.0'
prepare_react_native_project!

target 'Verification' do
  use_react_native!(
    :path => '../../node_modules/react-native',
    :app_path => File.expand_path('../..', __dir__),
    :hermes_enabled => false,
    :fabric_enabled => false
  )
  pod 'react-native-video', :path => '../../node_modules/react-native-video'
  pod 'StreamDownloader', :path => '../..'
  post_install do |installer|
    react_native_post_install(installer, '../../node_modules/react-native', :mac_catalyst_enabled => false)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
